# Generated by Django 6.0 on 2025-12-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('restaurant', 'Restaurant Staff'), ('laundry', 'Laundry Staff'), ('housekeeping', 'Housekeeping'), ('bar', 'Bar Staff')], default='receptionist', max_length=20),
        ),
    ]
